# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-13 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.IntegerField()),
                ('upass', models.CharField(max_length=100)),
            ],
        ),
    ]
