# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-29 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190129_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='technology',
            field=models.ForeignKey(default='Un-Category', on_delete=django.db.models.deletion.CASCADE, to='blog.Technology'),
        ),
    ]
