# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190129_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=25)),
                ('emp_dob', models.DateField(default=datetime.datetime.now)),
                ('emp_address', models.TextField()),
            ],
        ),
    ]
