# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_no',
            new_name='no',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_dob',
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
